# Generated by Django 4.0.2 on 2022-03-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='owner',
        ),
    ]
