# Generated by Django 4.0.2 on 2022-03-03 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercises_id_alter_workout_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
