# Generated by Django 4.0.2 on 2022-03-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercises_id_alter_workout_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='name',
        ),
    ]
