# Generated by Django 4.0.2 on 2022-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercises_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='pace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
